Change is_node_vein_diggable to not need for loops
echosa/mine_it_all pull request #5
Opened 2016-09-18 12:53 UTC by ben01189998819991197253

This changes the way vein-minable nodes are represented in mineable_nodes.lua. They can now be referenced using their name as their key (`mine_it_all.enabled_nodes["default:gravel"]`) instead of needing to loop over the entire collection and doing string comparison. This way, you can check whether a node is valid by simply trying to reference it with its name: if the result is nil, then it hasn't been put into the `enabled_nodes` table.

In a similar vein (pun intended), the way the valid tools for each node are stored has been changed so that you can check if a tool is valid by doing `node["default:tool_name"]`, instead of looping over each tool and doing string comparison. If the returned value is false or nil, then the tool cannot be used to vein-mine the node.

The performance benefits to doing it this way are so small as to be insignificant. But hypothetically, if there were 500 nodes in the `enabled_nodes` table, and 100 tools for each node, this would likely be the fastest way to determine if a given node were contained within it.

2016-09-18 16:05 UTC, echosa commented on mineable_nodes.lua
> +                ["default:shovel_wood"] = true,
I don't particularly care for having to set all of these to true like this. Hopefully, this will all be rewritten when #4 finally gets worked on, but for now, I like the idea of getting rid of the loops. Is there a way you can keep the tool names as values, not keys, and do an "in array" check? I'd really like to avoid having to have all the `true` values. It makes it seem like you should put `false`, which was not my original intention. The original intention was to either have the tool be listed, or not. Not to have all tools always be listed with either a true/false value. I supposed I could be convinced to keep it this way (until #4). State your case. :-)

2016-09-18 16:07 UTC, echosa commented on init.lua
> +    local node_vein = mine_it_all.enabled_nodes[node]
I don't think `node_vein` is a good variable name here. I think of the vein as the actual blocks in the game getting mined. This variable refers to a subset of the enabled nodes. Maybe a better variable name would be just `enabled_node` or something similar?

2016-09-18 16:08 UTC, echosa requested changes

2016-09-19 12:01 UTC, ben01189998819991197253 commented on init.lua
> +    local node_vein = mine_it_all.enabled_nodes[node]
I agree. I'll change that.

2016-09-19 12:09 UTC, ben01189998819991197253 commented on mineable_nodes.lua
> +                ["default:shovel_wood"] = true,
I see your point, it would be much more elegant to just assume that a tool works unless it's listed as being false. That actually already works. If you try to search for something that's not in the table, it'll return `nil`. In `is_node_vein_diggable`, it returns `false` if the result of looking for the tool is `nil`. It would be fairly straightforwards to just switch it all around (a step towards solving #4) and have it assume `true`, the tool works, if the result of trying to find it is `nil`. Then the only way for a tool to not work would be if you explicitly set it to `false`

Unfortunately I don't think I can get rid of assigning each tool's name to `true` or `false`. Lua doesn't seem to have a `contains()` method (like Java). But I can at least clear out the extra `true` entries.

2016-09-25 19:11 UTC, echosa approved these changes
Sorry I took so long to respond. I'll go ahead an approve these changes. I like the direct access instead of the nested loops, even if it does dirty up the config a bit.

2016-09-25 19:11 UTC, merged